# Generated by Django 3.2.7 on 2021-09-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiryform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=12)),
                ('place_of_study', models.CharField(max_length=100)),
                ('city_live', models.CharField(max_length=200)),
                ('course_interested', models.CharField(max_length=100)),
                ('phone_code', models.IntegerField()),
                ('hear', models.CharField(max_length=100, null=True)),
                ('mode_training', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=300)),
            ],
        ),
    ]
