# Generated by Django 3.2.7 on 2021-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduskillprojectapp', '0002_auto_20210918_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryform',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
