# Generated by Django 3.2.7 on 2022-01-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduskillprojectapp', '0004_enrollform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollform',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
